### ISSUE TITLE
Feature-list

### ISSUE THREAD

**Issue by baradhili** [ehidra/contact-tracer#7]
somewhere to initially triage features

**Comment by baradhili** [comment]
easily translatable

**Comment by baradhili** [comment]
country server? (easiest for privacy) or central server - easiest for management

**Comment by baradhili** [comment]
user button to release current location to authorities

**Comment by baradhili** [comment]
mechanism to advise IDs that they have been within 2m of a confirmed infection in the last 14-21 days

**Comment by Carglglz** [comment]
Hi @baradhili about this:

> mechanism to advise IDs that they have been within 2m of a confirmed infection in the last 14-21 days

I think we need to standardise a definition of "contact" and make sure everyone use the same definition, something like this [WHO case definition](https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200319-sitrep-59-covid-19.pdf?sfvrsn=c3dcdef9_2)
and this [NSW Government case definition](https://www.health.nsw.gov.au/Infectious/diseases/Pages/2019-ncov-case-definition.aspx)
but adapt this to BLE/ GPS data of a contact:
- BLE (short range) will help with data of the characteristics of a contact --> Exposure time and proximity
- GPS will help with data about where and when the contact was produced, and also when cases are confirmed, where are the hotspots.

From this data, I think it will be possible to do a risk assessment of every contact event and maybe determine how urgent a test and isolation are.

**Comment by baradhili** [comment]
GPS has lots of problems.. 1. is drains the battery, 2. privacy issue will reduce takeup - particularly Europe..
VS contact definition - I'm on a call with a network of Epidemology networks.. have a couple of contacts that will assist us with definitions etc... any automatic "contact" will be slightly vague anyway - there is no way to measure 2m 1.5m etc accurately on the fly..

**Comment by Carglglz** [comment]
I guess GPS does not need to be on all the time, it could just take a snapshot when new a contact is produced. 
And this data will only be shared if the person is tested positive, and it will be anonymised (So I guess health authorities need to do this part, and the app will take information from a reliable API?) .
I think this will help to see the big picture, how fast and far the virus is spreading within a region. 

>  I'm on a call with a network of Epidemology networks.

This is great 

> there is no way to measure 2m 1.5m etc accurately on the fly..

I think BLE RSSI should give a rough estimate, but yes I understand there are limitations [RSSI-Measurements](https://github.com/neXenio/BLE-Indoor-Positioning/wiki/RSSI-Measurements)

**Comment by 8lenka8** [comment]
Maybe more appropriate here:
One thing to consider is time. If we take bluetooth readings every minute, perhaps 'contact' should be >2-5 minutes, not anyone walking by on the street.
Then dataset size... 50 users over a month could generate 1/2 million data points. So preferably we want to aggregate contact data on device to day level...
Anonymity, masking MAC ids which are PPI data... looks like Singapore solution is handling it very well.
Alerting for every confirmed case contact will alert almost everyone. We can calculate simple probability e.g. if have several encounters or longer contacts the probability is higher.

**Comment by 8lenka8** [comment]
I think don't worry about whether BTE is 1.5 or 2m or more... Treat it the same for now. Once we have the data (very quick, contacts are exponential) and especially if we have feedback from confirmed cases, we'll be able to to 'sensitivity analysis' of how long in time a contact should be defined, how many contacts result in contagion etc

**Comment by waqarrashid33** [comment]
I agree with that. We have to parameterize the definition of contact so
that we can adjust it later when new research becomes available.

**Comment by baradhili** [comment]
Current definition of a contact is 15 min or more at a distance of 1.5m

**Comment by baradhili** [comment]
> Maybe more appropriate here:
> One thing to consider is time. If we take bluetooth readings every minute, perhaps 'contact' should be >2-5 minutes, not anyone walking by on the street.
> Then dataset size... 50 users over a month could generate 1/2 million data points. So preferably we want to aggregate contact data on device to day level...
> Anonymity, masking MAC ids which are PPI data... looks like Singapore solution is handling it very well.
> Alerting for every confirmed case contact will alert almost everyone. We can calculate simple probability e.g. if have several encounters or longer contacts the probability is higher.

we need to decay data stored by either 14 or 21 days.. and we really only need to store device id, timestamp on the device - which is what Singapore is doing as well..

**Comment by Carglglz** [comment]
Working with BLE beacons may be interesting as well for some use cases [Estimote](https://github.com/Estimote/Android-Proximity-SDK)

**Comment by baradhili** [comment]
BLE are nice yes.. but how to we manufacture billions of them? and convince people to use them? I think keeping to BLE has more chance of succeeding - this thread is really around getting a feature list that we can work through - right now the developer pool is too small to move fast..

**Comment by Carglglz** [comment]
>but how to we manufacture billions of them? and convince people to use them?

No, BLE beacons are not intended to be used by people, they exists already and are quite affordable. The use case would be to attach them in public transport or another space where a big gathering of people is expected. 
This way the app could detect the beacon and store the beacon's UUID and a Timestamp. 
Then if the person is tested positive, the people who have the same beacon's UUID stored and a "compatible" Timestamp would be notified. 

But yes, I'm aware this would be a feature for the the future, right now the priority is to have a MVP that gets attention and support from health authorities.

**Comment by amimem** [comment]
Hey guys, 

There are several institutes such as MILA who are trying to build an app with similar to yours.
Since I have had some experience with developing iOS SDKs and apps for beacons, I thought it might be a good idea to share the following problems with you:

"There are some technical challenges that one should tackle in order to build a user friendly app:
The user must receive notifications when the app is in the background or killed, so the best option would be to turn iOS devices into iBeacon transmitters, the firmware handles beacon signals that are received, so even if the app is killed you could still receive a notification. The problem is that iOS only allows transmitting beacon signals when the app is running in foreground.
Even if transmission was allowed in the background, you could not change the transmission power and thus the transmission range of the signals is iOS.
The other option is to start ranging when the presence of a beacon is detected, the value returned by ranging is not numerical, it is just a categorical distance such as far, near, immediate and unknown. This is because the distance is not accurate is many cases, and one should also account for attenuation and interference caused by walls and WiFi signals. Moreover, ranging is energy consuming, and it is not possible keep ranging when the app is killed, and if you keep ranging when the app is in the background, app store will most likely reject your app.
Another option is to use the geolocation of users and send them to a server and send push notifications to users who are too close to each other, the problem is that according to documentations “the receiver does its best to achieve the requested accuracy; however, the actual accuracy is not guaranteed“, and as we all know, getting a high accuracy is difficult in indoor locations in which social distancing is more crucial. After some Googling, my understanding is that an accuracy of less than 5 meters is not feasible in a lot of cases and could lead to false alarms and users would be eventually annoyed and would delete the app.”

I'd never use BLE for contact tracing on iOS; Even p2pkit has it's own limitations, and it is not maintained anymore.
Your best bet is to use Nearby, which facilitates things a little bit but again you can't set the advertisement range.
I think the best option to go for is geofencing at the moment.

**Comment by baradhili** [comment]
Thanks @amimem we are actually up and running with BLE.. its working for us though we need to start testing for realsies now

**Comment by amimem** [comment]
@baradhili My pleasure, I assume you are advertising a BLE service in the background and periodically scan for it, is that correct ?

**Comment by amimem** [comment]
I'm just curious to know how you handle the advertisement range if that is the case, and are you using additional data such as geolocation for that ?

**Comment by baradhili** [comment]
we don't right now.. but are looking into RSSI based ranging.. GPS isn't accurate to measure the 1.5m distance..

**Comment by amimem** [comment]
Thanks for your answer. That's a good idea, but RSSI readings are not that stable, which affect the user friendliness of the app. Maybe incorporating other data such as geolocation could help.

**Comment by baradhili** [comment]
yup.. but they are "rough enough"   geolocation has a bunch of problems.. inside it can be really bad, privacy people don't like it, and sometimes phone batteries get sucked dry fast which would result in our app being uninstalled.

Conceptually geolocation would be really good, but reality we don't think its good enough for the downsides...  On a stand-alone beacon it would be excellent.. but we don't have anyone working on those..

**Comment by baradhili** [comment]
@amimem if you want to help out.. can you drop me a line on Linkedin (/in/BretWatson) or on twitter (baradhili)? I can add you to slack

**Comment by amimem** [comment]
@baradhili Sure, I'd be glad to help, I have to warn you that I'm a student and may not be able to contribute much to the project :). I don't want to make a commitment that I cannot honor.
Just some ideas, if I'm not mistaken, a service and beacon cannot be advertised simultaneously, so disabling the service when app is the going to be killed and enabling beacon advertisement is a potential workaround for getting the app to work in all states (killed, background, foreground).

**Comment by amimem** [comment]
@baradhili I followed you on Twitter, I cannot send you a direct message though, here is my email:
amin.memarian@pm.me
